# Keep GitHub Actions and npm dependencies up to date.
# https://docs.github.com/en/code-security/dependabot

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ['actions/*']

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: '@playwright/test'
        update-types: [version-update:semver-major]
